name: FriskStick
version: 1.3.1 Alpha
main: friskstick.cops.plugin.FriskStick
description: >
             A plugin for checking for "drugs" on the player that is right clicked.
softdepend: [Essentials]
authors: [dchaosknight, domingocool]
commands:
  frisk:
    description: The command to frisk another player.
    usage: /frisk <player>
    permission: friskstick.chat
    permission-message: You don't have <permission> to frisk people.
  report:
    description: Allows players to report other players for drugs.
permissions:
  friskstick.*:
    description: All permissions.
    default: op
    children:
      friskstick.use: true
      friskstick.jail: true
      friskstick.chat: true
      friskstick.report.*: true
  friskstick.use:
    description: Allows a player to frisk another player.
    default: op
  friskstick.jail:
    description: Allows a player to jail another player after frisking.
    default: op
  friskstick.chat:
    description: Allows a player to use the /frisk command.
    default: op
  friskstick.report.*:
    description: Both of the report permissions.
    default: op
    children:
      friskstick.report.send: true
      friskstick.report.receive: true
  friskstick.report.send:
    description: Allows a player to report other players.
    default: true
  friskstick.report.receive:
    description: Allows a player to receive reports.
    default: op
  friskstick.notify:
    description: Notifies a player of updates.
    default: op
  friskstick.bypass:
    description: Allows a player to be immune to frisking.
    default: op